#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Author: booopooob@gmail.com
# 
# Info:
#
#

ONETIMEAUTH_BYTES = 10
ONETIMEAUTH_CHUNK_BYTES = 12
ONETIMEAUTH_CHUNK_DATA_LEN = 2


ADDRTYPE_AUTH = 0x10
ADDRTYPE_MASK = 0xF

TCP_BUF_SIZE = 1024 * 32

# FOR SOCKS5
SOCKS5_VERSION = 0x05
SOCKS5_METHOD_NO_AUTHENTICATION_REQUIRED = 0x00
SOCKS5_METHOD_GSSAPI = 0x01
SOCKS5_METHOD_USERNAME_PASSWORD = 0x02
SOCKS5_METHOD_NO_ACCEPTABLE_METHODS = 0xFF
# SOCKS command definition
SOCKS5_CMD_CONNECT = 1
SOCKS5_CMD_BIND = 2
SOCKS5_CMD_UDP_ASSOCIATE = 3

SOCKS5_REPLY_SUCCEEDED = 0x00
SOCKS5_REPLY_GENERAL_SOCKS_SERVER_FAILURE = 0x01
SOCKS5_REPLY_CONNECTION_NOT_ALLOWED_BY_RULESET = 0x02
SOCKS5_REPLY_NETWORK_UNREACHABLE = 0x03
SOCKS5_REPLY_HOST_UNREACHABLE = 0x04
SOCKS5_REPLY_CONNECTION_REFUSED = 0x05
SOCKS5_REPLY_TTL_EXPIRED = 0x06
SOCKS5_REPLY_COMMAND_NOT_SUPPORTED = 0x07
SOCKS_REPLY_ADDRESS_TYPE_NOT_SUPPORTED = 0x08

SOCKS5_RESERVED_BYTE = 0x00
# use the value defined by SOCKS5 protocal
SOCKS5_ADDRTYPE_IPV4 = 0x01
SOCKS5_ADDRTYPE_IPV6 = 0x04
SOCKS5_ADDRTYPE_HOST = 0x03
